name: deploy

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      # version:
      #   description: 'Name of version (ie 5.5.0)'
      #   required: true

jobs:
  prebuild-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: wget "https://www.foundationdb.org/downloads/6.3.13/ubuntu/installers/foundationdb-clients_6.3.13-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-clients_6.3.13-1_amd64.deb
    - run: sudo mkdir -p /var/lib/foundationdb/data
    - run: wget "https://www.foundationdb.org/downloads/6.3.13/ubuntu/installers/foundationdb-server_6.3.13-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-server_6.3.13-1_amd64.deb

    - run: yarn
    - run: yarn prebuild
    - run: yarn test

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: prebuilds/linux-x64
        retention-days: 5

  prebuild-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: wget "https://www.foundationdb.org/downloads/6.3.13/macOS/installers/FoundationDB-6.3.13.pkg"
    - run: sudo installer -pkg FoundationDB-6.3.13.pkg -target /

    - run: yarn
    - run: yarn prebuild

    # Build for apple M1 and make sure the prebuilt module actually has arm64 code
    # Blocked by https://github.com/actions/virtual-environments/issues/2486
    # - run: yarn prebuild --arch arm64
    # - run: lipo -archs prebuilds/darwin-arm64/node.napi.node | grep -q arm64

    - run: yarn test

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: darwin-x64
        path: prebuilds/darwin-x64
        retention-days: 5

  prebuild-windows:
    runs-on: windows-latest
    env:
      FOUNDATIONDB_INSTALL_PATH: "C:\\Program Files\\FoundationDB"

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: (new-object net.webclient).DownloadFile('https://www.foundationdb.org/downloads/6.3.12/windows/installers/foundationdb-6.3.12-x64.msi', 'c:\foundationdb.msi')
    - run: dir c:\foundationdb.msi
    - run: msiexec /i c:\foundationdb.msi /quiet /passive /norestart /log install.log | Out-Null

    - run: echo "C:\\Program Files\\FoundationDB\bin" >> $GITHUB_PATH

    - run: yarn
    - run: yarn prebuild
    
    # For some reason this test fails - it can't find the prebuild even though its *right there*!!
    # - run: yarn test
    # - run: Get-ChildItem -Recurse prebuild

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win32-x64
        path: prebuilds/win32-x64
        retention-days: 5

  deploy-npm:
    needs: [prebuild-windows, prebuild-macos, prebuild-linux]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

    - uses: actions/download-artifact@v2
      with:
        path: prebuilds

    - run: ls -R prebuilds

    # Ideally I shouldn't need this...
    - run: wget "https://www.foundationdb.org/downloads/6.3.13/ubuntu/installers/foundationdb-clients_6.3.13-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-clients_6.3.13-1_amd64.deb

    # And I could just run the linux script last anyway.
    - run: yarn
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
